<?php 

function feeds_gmaps_parser_feeds_plugins() {
	$info = array();
	$info['FeedsGMapsParser'] = array(
	   'name' => 'Google Maps GeoRSS parser',
	   'description' => 'Parse GeoRSS feeds from Google Maps.',
	   'handler' => array(
	       'parent' => 'FeedsParser',
	       'class' => 'FeedsGMapsParser',
	       'file' => 'FeedsGMapsParser.inc',
	       'path' => drupal_get_path('module', 'feeds_gmaps_parser'),
	   ),
	);
	return $info;
}

/**
 * Implementation of hook_feeds_term_processor_targets_alter().
 *
 * Expose possible mapping targets for taxonomy terms. If a user picks these
 * targets, FeedsTermProcessor will stick their values on $term['lat'],
 * $term['lon'] and so forth.
 */
function feeds_gmaps_parser_feeds_term_processor_targets_alter(&$targets, $vid) {
  $vocabulary_settings = variable_get('geotaxonomy_vocabularies', array());
  if ($vocabulary_settings[$vid]) {
    $targets['lat'] = array(
      'name' => t('Latitude'),
      'description' => t('Latitude of the geo term.'),
    );
    $targets['lon'] = array(
      'name' => t('Longitude'),
      'description' => t('Longitude of the geo term.'),
    );
    $targets['bound_top'] = array(
      'name' => t('Top boundary'),
      'description' => t('Top boundary latitude to be used when displaying this term on a map.'),
    );
    $targets['bound_right'] = array(
      'name' => t('Right boundary'),
      'description' => t('Right boundary longitude to be used when displaying this term on a map.'),
    );
    $targets['bound_bottom'] = array(
      'name' => t('Bottom boundary'),
      'description' => t('Bottom boundary latitude to be used when displaying this term on a map.'),
    );
    $targets['bound_left'] = array(
      'name' => t('Left boundary'),
      'description' => t('Left boundary longitude to be used when displaying this term on a map.'),
    );
    $targets['geometry'] = array(
      'name' => t('Geometry'),
      'description' => t('WKT Geometry'),
    );
    $targets['parent_name'] = array(
      'name' => t('Parent term name'),
      'description' => t('The name of this term\'s parent term. Used to compute hierarchies of geo terms.'),
    );
    $targets['external_id'] = array(
      'name' => t('External ID'),
      'description' => t('An external id of this term. Can be useful when dealing with ambigous geo terms (e. g. Paris, Illinois vs. Paris, France).'),
    );
    $targets['parent_external_id'] = array(
      'name' => t('Parent external ID'),
      'description' => t('The external ID of this term\'s parent term. Used to compute hierarchies of geo terms.'),
    );
  }
}