<?php
// $Id: flash.inc,v 1.3 2009/01/15 20:01:15 jtsnow Exp $

//function embed_widgets_iframe_info() {
//  return "I am iFrame!";
//}
//
//class flash extends widget_format {
//
//  public function get_code($widget) {
//
//  }
//  
//  public function content() {
//    
//  }
//  
//  public function embed() {
//
//  }
//  
//  public function get_filename() {
//    
//  }
//  
//  public function preview($widget, $theme = NULL) {
//    return $this->get_code($widget);
//  }
//  
//  public function live_preview($widget, $theme = NULL) {
//
//  }
//  
//  static function settings_form() {
//    
//  }
//  
//  static function admin_settings() {
//    $form = array();
//    return $form;
//  }
//  
//  public function allowed_themes() {
//    
//  }
//
//}
