<?php
// $Id: feeds_xpathparser.module,v 1.1 2010/06/28 01:45:50 twistor Exp $

/**
 * Implementation of hook_feeds_plugins().
 */
function feeds_xpathparser_feeds_plugins() {
  $info = array();
  $info['FeedsXPathParser'] = array(
    'name'        => t('XPath parser'),
    'description' => t('Queries a XML or HTML document using XPath.'),
    'handler'     => array(
      'parent' => 'FeedsParser', // A plugin needs to derive either directly or indirectly from FeedsFetcher, FeedsParser or FeedsProcessor.
      'class'  => 'FeedsXPathParser',
      'file'   => 'FeedsXPathParser.inc',
      'path'   => drupal_get_path('module', 'feeds_xpathparser'),
    ),
  );
  return $info;
}
