<?php
// $Id $

// Guernsey
// See http://www.statoids.com/ugg.html

function location_province_list_gg() {
  return array(
    'AL' => 'Alderney',
    'BQ' => 'Brecqhou',
    'CA' => 'Castel',
    'FO' => 'Forest',
    'HM' => 'Herm',
    'JT' => 'Jethou',
    'LH' => 'Lihou',
    'AN' => 'Saint Andrew',
    'MA' => 'Saint Martin',
    'PP' => 'Saint Peter Port',
    'PB' => 'Saint Pierre du Bois',
    'SM' => 'Saint Sampson',
    'SV' => 'Saint Saviour',
    'SK' => 'Sark',
    'TV' => 'Torteval',
    'VA' => 'Vale',
  );
}
