<?php
// $Id $

// Jersey
// See http://www.statoids.com/uje.html

function location_province_list_je() {
  return array(
    'GR' => 'Grouville',
    'BR' => 'Saint Brelade',
    'CL' => 'Saint Clement',
    'HE' => 'Saint Helier',
    'JO' => 'Saint John',
    'LA' => 'Saint Lawrence',
    'MT' => 'Saint Martin',
    'MY' => 'Saint Mary',
    'OU' => 'Saint Ouen',
    'PE' => 'Saint Peter',
    'SA' => 'Saint Saviour',
    'TR' => 'Trinity',
  );
}
